/*
   Title: AS3Registry.hx
*/

/*
   Interface: AS3Registry
      Keeps track of class stubs generated by import functions.
*/
interface AS3Registry {
   /*
      Function: getContext

         Returns the AS3 context for the actual frame.

      Returns:

         The AS3 context for the actual frame.
   */
   function getContext(): format.abc.Context;
}
